language: node_js
node_js:
- '0.10'
deploy:
  provider: s3
  access_key_id: AKIAJ7SXC23CS2USONIA
  secret_access_key:
    secure: bdxa1ccX7sk9AzilOQx5IAVsCutMkOmZx6kapqrCu25qRkyEdMy+mYYLTwPzsj02Wyzx7zNmlRLASLYwmxOqFEYJCjrRIZr359AoYeQNExj3QJMyA8BOgPGvGAOCFnIaHeZvfa1R2sNm62P8EyTmYE6ECE7FN+c3j/uiyR+hQoE=
  bucket: biojs
  upload-dir: bio/latest
  acl: public-read
  detect_encoding: true # allow compressed uploads
  skip_cleanup: true
  local-dir: build
  on:
      repo: biojs/bio
