language: node_js
node_js:
- '0.10'
deploy:
  provider: s3
  access_key_id: AKIAJ7SXC23CS2USONIA
  secret_access_key:
    secure: GdaaJcZesB66rHXoo02hJwnqRztzdYPX2YwN0xWM827YPo6JoyCLpb5kCNTAjiU/SE6BCrYDi+sbgIMAVPC8YIpBRG1gpAgOicWJsLkwv44VsOQBPI49/nvY+v+5xWqtthO8leGEji570whnZrMIna3WO4F/YmkksChCsEJrPXY=
  bucket: biojs
  upload-dir: bio/latest
  acl: public-read
  detect_encoding: true # allow compressed uploads
  skip_cleanup: true
  local-dir: build
  on:
      repo: biojs/bio
