language: node_js
node_js:
- '0.10'
deploy:
  provider: s3
  access_key_id: AKIAIUBRKBVSD3LAFBUQ
  secret_access_key: 
    secure: NWOlbiOAVFHcWEaK/G6j7BZiqotx6/U5EMlaK2xkMNn/ZZ27I504EJoDKJHBU5Ar3EAqp3hHmR5wCC07DAOi20zdL8vyh5nBZyQSKjFxsiSxgoRsrxmLcTbdKfpEnhU7cEhkuG15Qt7NIg7ZwtN7GCyhZCu4Dd1d8RiV0efFf+E=
  bucket: cdn.biojs.net
  upload-dir: bio/latest
  acl: public-read
  detect_encoding: true
  skip_cleanup: true
  local-dir: build
  region: eu-west-1
  on:
    repo: biojs/bio
